"""
Structured markdown report generation and terminal display utilities.
"""

import os
from datetime import datetime

from config import OUTPUT_DIR, AGENT_NAME


class ReportGenerator:
    """Generates, formats, and saves structured markdown reports."""

    def __init__(self):
        """Initialize and ensure the output directory exists."""
        os.makedirs(OUTPUT_DIR, exist_ok=True)

    def get_header(self, title):
        """
        Return a formatted report header with the agent name and current timestamp.
        This header appears at the top of every saved report.
        """
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        return (
            f"# {title}\n\n"
            f"Generated by {AGENT_NAME}  \n"
            f"Timestamp: {timestamp}\n\n"
            "---\n\n"
        )

    def save_report(self, filename, content):
        """
        Write report content to a file in the output directory.
        Returns the full path of the saved file.
        """
        filepath = os.path.join(OUTPUT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(content)
        return filepath

    def make_filename(self, prefix, slug):
        """
        Generate a timestamped filename for a report.
        Non alphanumeric characters in the slug are replaced with underscores.
        """
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        safe_slug = "".join(c if c.isalnum() else "_" for c in slug)[:40]
        return f"{prefix}_{safe_slug}_{timestamp}.md"

    def format_table(self, headers, rows):
        """
        Render a list of rows as a plain text table with aligned columns.
        headers is a list of column header strings.
        rows is a list of lists where each inner list is one row.
        Returns the table as a single string.
        """
        col_widths = [len(str(h)) for h in headers]
        for row in rows:
            for i, cell in enumerate(row):
                col_widths[i] = max(col_widths[i], len(str(cell)))

        separator = "+" + "+".join("-" * (w + 2) for w in col_widths) + "+"
        header_row = (
            "|"
            + "|".join(
                f" {str(h):<{col_widths[i]}} " for i, h in enumerate(headers)
            )
            + "|"
        )

        lines = [separator, header_row, separator]
        for row in rows:
            line = (
                "|"
                + "|".join(
                    f" {str(cell):<{col_widths[i]}} "
                    for i, cell in enumerate(row)
                )
                + "|"
            )
            lines.append(line)
        lines.append(separator)
        return "\n".join(lines)

    def print_table(self, headers, rows, title=None):
        """
        Print a formatted table to the terminal with an optional title.
        If no rows are provided, prints a message indicating no data was found.
        """
        if title:
            print(f"\n{title}")
            print("=" * len(title))
        if not rows:
            print("  No data to display.")
            return
        table = self.format_table(headers, rows)
        print()
        print(table)
        print()
